version: '3.1'

services:

  mongo:
    # source:
    # https://hub.docker.com/_/mongo
    image: mongo:4.4-bionic

    container_name: mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    volumes:
      - ./mongo_data:/data/db:rw
    
    restart: always

  webserver:

    image: online-magazine:ver-1

    container_name: webserver

    build:
      context: ./base/.
    
    ports:
      - "80:3345"

    depends_on: 
      - mongo 

    command: /app/docker-entrypoint.sh

    restart: always
