version: "3.7"

services:
    mysql:
        # image-docu: https://hub.docker.com/_/mysql
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        # restart: always
        environment:
            MYSQL_ROOT_PASSWORD: q3209458avbnrqJFIHEW
            MYSQL_DATABASE: database
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: fbw47-2assassins

        #volumes: # nach Bedarf:
        #    - "./db_data:/var/lib/mysql:rw"
        #    - "./sql:/docker-entrypoint-initdb.d:ro"

    cli:
        build:
            context: ./cli
        environment:
            MYSQL_HOST: mysql
            #MYSQL_TCP_PORT: 3306
            MYSQL_PWD: fbw47-2assassins
    
        volumes:
            - "./sql:/sql:rw"

        command: /bin/bash

    phpmyadmin:
        # image-docu: https://hub.docker.com/_/phpmyadmin
        image: phpmyadmin:5-apache
        #restart: always
        ports:
            - 8080:80
        environment:
            PMA_ARBITRARY: 1
            MYSQL_ROOT_PASSWORD: q3209458avbnrqJFIHEW
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: fbw47-2assassins

