version: '3.1'

services:

mongo:
  # source:
  # https://hub.docker.com/_/mongo
  image: mongo:4.4-bionic

  environment:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: example
  #restart: always

  webserver:
    build:
      context: ./base/.

  ports:
    - "3345:3345"

  depends_on:
    - mongo

  command: /app/docker-entrypoint.sh